stages:
  - code_review

variables:
  NODE_ENV: production

code_review:
  stage: code_review
  image: node:20
  script:
    # 1️⃣ 安装依赖
    - npm ci

    # 2️⃣ 编译项目
    - npm run build

    # 3️⃣ 执行 AI 审查（调用 NestJS webhook）
    - node dist/review-action.js
  only:
    refs:
      - branches
    variables:
      - $CI_MERGE_REQUEST_ID  # 仅在 MR 下触发
  when: on_success
  # 手动触发
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: manual

  # 环境变量传入
  variables:
    # GitLab
    GITLAB_ACCESS_TOKEN: $GITLAB_ACCESS_TOKEN
    GITLAB_URL: $GITLAB_URL

    # GitHub（兼容调用 GitHub API 的情况）
    GITHUB_ACCESS_TOKEN: $GITHUB_ACCESS_TOKEN
    GITHUB_URL: $GITHUB_URL

    # 数据库
    MONGODB_URI: $MONGODB_URI

    # LLM 配置
    LLM_PROVIDER: $LLM_PROVIDER
    DEEPSEEK_API_KEY: $DEEPSEEK_API_KEY
    OPENAI_API_KEY: $OPENAI_API_KEY
    QWEN_API_KEY: $QWEN_API_KEY
    ZHIPUAI_API_KEY: $ZHIPUAI_API_KEY
    OLLAMA_BASE_URL: $OLLAMA_BASE_URL

    # 通知
    DINGTALK_ENABLED: $DINGTALK_ENABLED
    DINGTALK_WEBHOOK_URL: $DINGTALK_WEBHOOK_URL
    WECOM_ENABLED: $WECOM_ENABLED
    WECOM_WEBHOOK_URL: $WECOM_WEBHOOK_URL
    FEISHU_ENABLED: $FEISHU_ENABLED
    FEISHU_WEBHOOK_URL: $FEISHU_WEBHOOK_URL

    # 审查配置
    SUPPORTED_EXTENSIONS: $SUPPORTED_EXTENSIONS
    PUSH_REVIEW_ENABLED: $PUSH_REVIEW_ENABLED
    REPORT_CRONTAB_EXPRESSION: $REPORT_CRONTAB_EXPRESSION

    # 日志
    LOG_LEVEL: $LOG_LEVEL
