# ==========================================
# .codereview.yaml
# AI 自动代码审查配置
# ==========================================

version: 1.0

# ------------------------------------------
# 基础设置
# ------------------------------------------
review:
  enabled: true # 是否启用自动审查
  language: zh # 审查语言，可选 zh / en
  mode: strict # 审查模式：light / strict
  max_review_length: 4000 # 单次审查输出最大长度（字符数）
  max_files: 50 # 超过此文件数跳过审查
  max_content_length: 20000 # 单文件最大内容长度（字符数）

# ------------------------------------------
# 文件类型与路径规则
# ------------------------------------------
files:
  extensions:
    - .js
    - .ts
    - .vue
    - .py
    - .java
    - .yml
    - .json
    - .md
    - .sql
  include:
    - 'src/**/*'
    - 'app/**/*'
  exclude:
    - 'dist/**/*'
    - 'node_modules/**/*'
    - 'test/**/*'
    - '**/*.min.js'

# ------------------------------------------
# 触发规则
# ------------------------------------------
trigger:
  events: # 触发类型（支持 pull_request / push）
    - pull_request
    - push
  branches: # 限定触发分支
    - develop
  include_draft: false # 是否包含 Draft PR

  ignore_rules: # 排除规则
    title_contains: # PR 标题包含以下内容则跳过审查
      - WIP
      - Draft
      - DO NOT REVIEW
    branch_matches: # 分支匹配以下规则则跳过审查
      - feature/*
      - hotfix/*
      - release/*
      - master
      - main
      - develop

# ------------------------------------------
# 通知与任务集成
# ------------------------------------------
integrations:
  dingtalk:
    notification:
      enabled: true
      template: |
        🚀 代码审查完成
        状态: {{ status }}
        问题数: {{ issues }}
        严重问题: {{ critical }}
        审查人: AI CodeReviewer

  pingcode:
    notification:
      enabled: true
      template: |
        🚀 代码审查完成
        状态: {{ status }}
        问题数: {{ issues }}
        严重问题: {{ critical }}
        审查人: AI CodeReviewer

    push_summary: # 自动写入任务自定义字段
      enabled: true
      summary_field: ai_review_summary
      template: |
        🚀 代码审查完成
        状态: {{ status }}
        问题数: {{ issues }}
        严重问题: {{ critical }}
        审查人: AI CodeReviewer

# ------------------------------------------
# 参考资料
# ------------------------------------------
references:
  - path: './docs/code-style.md'
  - url: 'https://example.com/security-guidelines'
  - url: 'https://example.com/performance-checklist'
