version: '1.0'

review:
  enabled: true
  language: 'zh'
  mode: 'strict'
  max_review_length: 4000
  max_files: 50
  max_content_length: 20000

files:
  extensions:
    - '.js'
    - '.ts'
    - '.vue'
    - '.py'
    - '.java'
    - '.yml'
    - '.json'
    - '.md'
    - '.sql'
  include:
    - '**/*'
  exclude:
    - 'dist/**/*'
    - 'node_modules/**/*'
    - 'test/**/*'
    - '**/*.min.js'
    - '**/*.min.css'

trigger:
  events:
    - 'pull_request'
    - 'push'
  branches:
    - 'master'
    - 'develop'
  include_draft: false
  ignore_rules:
    title_contains:
      - 'WIP'
      - 'Draft'
      - 'DO NOT REVIEW'
    branch_matches:
      - 'release/*'

# 代码规范配置示例
codeStandards:
  enabled: true
  sources:
    # 内联配置
    - type: 'inline'
      content: |
        rules:
          - id: 'naming-convention'
            name: '命名规范'
            description: '变量和函数名应该使用驼峰命名法'
            severity: 'warning'
            category: 'naming'
            examples:
              - bad: 'var user_name = "test"'
                good: 'var userName = "test"'
          - id: 'no-console'
            name: '禁止使用console'
            description: '生产代码中不应该包含console语句'
            severity: 'error'
            category: 'best-practices'
            examples:
              - bad: 'console.log("debug info")'
                good: 'logger.info("debug info")'
      format: 'yaml'
      priority: 1

    # 从仓库文件加载
    - type: 'file'
      path: './.code-standards.yaml'
      format: 'yaml'
      priority: 2

    # 从外部URL加载
    - type: 'url'
      url: 'https://raw.githubusercontent.com/example/standards/main/typescript-rules.yaml'
      format: 'yaml'
      priority: 3

    # 从Markdown文档加载
    - type: 'file'
      path: './docs/code-standards.md'
      format: 'markdown'
      priority: 4

references:
  - path: './docs/code-style.md'
  - url: 'https://example.com/security-guidelines'
  - url: 'https://example.com/performance-checklist'
