name: Ping AI Reviewer

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, master, develop]
  workflow_dispatch: # 支持手动触发

permissions:
  contents: read       # 读取仓库文件
  pull-requests: write # 向 PR 添加评论

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ 拉取仓库完整代码
      - name: Checkout 仓库代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ 安装 Node.js 20
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ 安装依赖
      - name: 安装依赖
        run: npm ci


      # 4️⃣ 构建项目
      - name: 编译项目
        run: npm run build

      # 5️⃣  执行 AI 审查
      - name: 执行 AI 代码审查
        run: node dist/review-action.js
        env:
          # 环境变量配置
          NODE_ENV: production
          # GitHub 相关
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          GITHUB_URL: ${{ secrets.GITHUB_URL }}

          # GitLab 兼容
          GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
          GITLAB_URL: ${{ secrets.GITLAB_URL }}

          # 数据库
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

          # LLM 配置
          LLM_PROVIDER: ${{ secrets.LLM_PROVIDER }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          QWEN_API_KEY: ${{ secrets.QWEN_API_KEY }}
          ZHIPUAI_API_KEY: ${{ secrets.ZHIPUAI_API_KEY }}
          OLLAMA_BASE_URL: ${{ secrets.OLLAMA_BASE_URL }}

          # 通知
          DINGTALK_ENABLED: ${{ secrets.DINGTALK_ENABLED }}
          DINGTALK_WEBHOOK_URL: ${{ secrets.DINGTALK_WEBHOOK_URL }}
          WECOM_ENABLED: ${{ secrets.WECOM_ENABLED }}
          WECOM_WEBHOOK_URL: ${{ secrets.WECOM_WEBHOOK_URL }}
          FEISHU_ENABLED: ${{ secrets.FEISHU_ENABLED }}
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}

          # 审查配置
          SUPPORTED_EXTENSIONS: ${{ secrets.SUPPORTED_EXTENSIONS }}
          PUSH_REVIEW_ENABLED: ${{ secrets.PUSH_REVIEW_ENABLED }}
          REPORT_CRONTAB_EXPRESSION: ${{ secrets.REPORT_CRONTAB_EXPRESSION }}

          # 日志配置
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
